site_name: tcprojWrapper
repo_url: https://github.com/topcoderinc/tcProjWrapper
pages:
    - tcProjWrapper:
      - 'Project introduction': index.md
      - mkdocs: mkDocsIndex.md
    - Todo: Todo.md
theme_dir: cinder/site
