site_name: tcprojWrapper
repo_url: https://github.com/topcoderinc/tcProjWrapper
pages:
    - 'Topcoder Docs':
       - 'Copilot Responsibilities': topcoder/copilotsResponsiblites.md
       - code:
          - 'Fixing Bugs from github': topcoder/fixingBugs.md
          - 'Ragnar: Git Process': topcoder/RagnarGit.md
    - tcProjWrapper:
      - 'This Project introduction': index.md
      - mkdocs: mkDocsIndex.md
    - Project: project.md
theme_dir: cinder/site
